[package]
name = "etl-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
env_logger = "0.11"
csv = "1.4.0"

serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
