[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.11.0"
wasm-bindgen = "0.2.106"
wasm-bindgen-rayon = "1.3.0"
num-complex = "0.4"

[lib]
crate-type = ["cdylib", "rlib"]